admin:
  resource: "@MainBundle/Resources/config/routing-admin.yml"
  prefix:   /admin/{_locale}/

main:
  resource: "@MainBundle/Resources/config/routing.yml"
  prefix:   /
  requirements:
    _locale:  en|fr

xs_market_place:
  resource: "@XSMarketPlaceBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/market

logout:
  path: /logout
