admin:
  resource: "@MainBundle/Resources/config/routing-admin.yml"
  prefix:   /{_locale}/admin

main:
  resource: "@MainBundle/Resources/config/routing.yml"
  prefix:   /
  requirements:
    _locale:  en|fr

xs_market_place:
  resource: "@XSMarketPlaceBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/market

xs_afrobank:
  resource: "@XSAfrobankBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/bank

logout:
  path: /logout
