xs_afrobank_paypal_homepage:
  path: /
  defaults: { _controller: XSAfrobankBundle:PayPal:index }

xs_afrobank_paypal_order_add:
  path: /paypal/orders/add
  defaults: { _controller: XSAfrobankBundle:PayPal:addOrder }