#Dashboard de gestion des artistes
admin_homepage:
  path:     /
  defaults: { _controller: MainBundle:Admin:index }

admin_store:
  path:     /store
  defaults: { _controller: MainBundle:Admin:index }

#Admin User

admin_profile:
  path:     /me
  defaults: { _controller: MainBundle:Admin:index }

admin_profile_playlist:
#  Musics achetées
  path:     /me/playlist
  defaults: { _controller: MainBundle:Admin:playlist }

admin_profile_playlist_album:
#  Musics achetées
  path:     /me/playlist/albums/{id}
  defaults: { _controller: MainBundle:Admin:playlistAlbumShow }

admin_profile_favorites:
#  Musics favorites
  path:     /me/favorites
  defaults: { _controller: MainBundle:Admin:favorites }

#Admin Artist
admin_artists:
  prefix:     /artists
  resource: "admin/routing-artists.yml"

admin_albums:
  prefix:     /albums
  resource: "admin/routing-albums.yml"

admin_musics:
  prefix:     /musics
  resource: "admin/routing-musics.yml"