#Dashboard de gestion des artistes
admin_homepage:
  path:     /
  defaults: { _controller: MainBundle:Admin:index }

admin_store:
  path:     /store
  defaults: { _controller: MainBundle:Admin:index }

#Admin User

admin_profile:
  path:     /me
  defaults: { _controller: MainBundle:Admin:index }

admin_profile_playlist:
#  Musics achetées
  path:     /me/playlist
  defaults: { _controller: MainBundle:Admin:playlist }

admin_profile_playlist_album:
#  Musics achetées
  path:     /me/playlist/albums/{id}
  defaults: { _controller: MainBundle:Admin:playlistAlbumShow }

admin_profile_favorites:
#  Musics favorites
  path:     /me/favorites
  defaults: { _controller: MainBundle:Admin:favorites }

admin_profile_favorites_add_album:
  #  Ajouter un album aux favoris
  path:     /me/favorites/albums/add/{id}
  defaults: { _controller: MainBundle:Admin:favoriteAlbumAdd }

admin_profile_favorites_remove_album:
  #  Ajouter un album aux favoris
  path:     /me/favorites/albums/remove/{id}
  defaults: { _controller: MainBundle:Admin:favoriteAlbumRemove }

admin_profile_favorites_add_music:
  #  Ajouter un music aux favoris
  path:     /me/favorites/musics/add/{id}
  defaults: { _controller: MainBundle:Admin:favoriteMusicAdd }

admin_profile_favorites_remove_music:
  #  Ajouter un music aux favoris
  path:     /me/favorites/musics/remove/{id}
  defaults: { _controller: MainBundle:Admin:favoriteMusicRemove }

#Admin User
#rendre/retirer Artiste, réinitialiser le compte
admin_users:
  prefix:     /users
  resource: "admin/routing-users.yml"

#Admin Bank
#Gérer les finances : paiements et transactions
admin_dashboard:
  path:     /dashboard
  defaults: { _controller: MainBundle:Admin:dashboard }
#  resource: "admin/routing-finances.yml"

#Admin Artist
admin_artists:
  prefix:     /artists
  resource: "admin/routing-artists.yml"

admin_albums:
  prefix:     /albums
  resource: "admin/routing-albums.yml"

admin_musics:
  prefix:     /musics
  resource: "admin/routing-musics.yml"