main_homepage:
    path:     /{_locale}
    defaults: { _controller: MainBundle:Default:index, _locale: en_EN  }

api_business_card:
    path:     /{_locale}/business-cards/{id}
    defaults: { _controller: MainBundle:Api:businessCard, _locale: en_EN  }

api_get_order:
    path:     /{_locale}/get-order/{id}
    defaults: { _controller: MainBundle:Api:getOrder, _locale: en_EN  }

edu_homepage:
  path:     /{_locale}/edu
  defaults: { _controller: MainBundle:Edu:index, _locale: en_EN }
