promo:
    path:     /promo
    defaults: { _controller: MainBundle:Default:index, _locale: fr  }

gtag_artist:
  #  Tous les artistes
  path:     /artists
  defaults: { _controller: MainBundle:Core\Artist:index }



main_homepage:
    path:     /{_locale}
    defaults: { _controller: MainBundle:Default:index, _locale: fr  }

main_artists:
  prefix:   /{_locale}/artists
  resource: "core/routing-artists.yml"

api_business_card:
    path:     /{_locale}/business-cards/{id}
    defaults: { _controller: MainBundle:Api:businessCard, _locale: fr  }

api_get_order:
    path:     /{_locale}/get-order/{id}
    defaults: { _controller: MainBundle:Api:getOrder, _locale: fr  }

edu_homepage:
  path:     /{_locale}/edu
  defaults: { _controller: MainBundle:Edu:index, _locale: fr }

login:
  path: /{_locale}/login
  defaults: { _controller: XSUserBundle:Security:login }

login_check:
  path: /{_locale}/login_check

signin:
  path: /{_locale}/signin
  defaults: { _controller: XSUserBundle:Security:signin }
